### ISSUE TITLE
Physical::Box should not have infinite length dimensions

### ISSUE THREAD

**Issue by tvdeyen** [mamhoff/physical#17]
A `Physical::Package` has a default container that has infinite length dimensions. This turned out to not be a good idea. If one makes calculations - in worst case divisions - we end up with `FloatDomainError`. In real world there are no carriers that ship the universe as package. All known carriers work with 0 as dimensions of a "null" box. Maybe we should adjust to that and make the default 0 instead?

**Comment by mamhoff** [comment]
I think that's correct actually. We should get errors when trying to calculate with unknown dimensions. 

The alternatives would be using `nil` (which would yield `undefined method for nilClass`), or using `0`, which would make us end up with negative numbers or zero where we don't expect it. I'd say let's keep it this way and handle those errors in the calling code.
